### ISSUE TITLE
Airbrake incompatibilty

### ISSUE THREAD

**Issue by joel** [cloudfuji/airbrake_user_attributes#8]
- airbrake_user_attributes-0.1.6
- airbrake-3.1.17

```
Airbrake.notify(Exception.new('oups'))
** [Airbrake] [Airbrake::Sender#send_to_airbrake] Cannot send notification. Error: ArgumentError - wrong number of arguments (0 for 1)
Backtrace:
/Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:34:in `method'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:34:in `block (4 levels) in to_xml'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:31:in `each'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:31:in `block (3 levels) in to_xml'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:30:in `block (2 levels) in to_xml'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:27:in `block in to_xml'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake_user_attributes-0.1.6/lib/airbrake_overrides/notice.rb:20:in `to_xml'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake-3.1.17/lib/airbrake/sender.rb:115:in `prepare_notice'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake-3.1.17/lib/airbrake/sender.rb:50:in `send_to_airbrake'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake-3.1.17/lib/airbrake.rb:161:in `send_notice'
    /Users/joel/.rvm/gems/ruby-2.1.3@finalcloud/gems/airbrake-3.1.17/lib/airbrake.rb:126:in `notify'
    (irb):2:in `irb_binding'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/workspace.rb:86:in `eval'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/workspace.rb:86:in `evaluate'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/context.rb:380:in `evaluate'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:492:in `block (2 levels) in eval_input'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:489:in `block in eval_input'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:397:in `block in start'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:396:in `catch'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/irb.rb:396:in `start'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
    /Users/joel/Documents/WorkData/RubyWorkSpace/KnowledgeCorp/finalcloud/bin/rails:10:in `<top (required)>'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/commands/rails.rb:6:in `call'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/command_wrapper.rb:38:in `call'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:180:in `block in serve'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:153:in `fork'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:153:in `serve'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
    /Users/joel/.rvm/gems/ruby-2.1.3@global/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    -e:1:in `<main>'
** [Airbrake] Environment Info: [Ruby: 2.1.3] [Rails: 4.1.6] [Env: development]
=> nil
```

**Comment by softcraft-development** [comment]
I'm getting the same issue.

**Comment by softcraft-development** [comment]
It was an easy fix; see my pull request: https://github.com/cloudfuji/airbrake_user_attributes/pull/9

However, it looks like the whole gem might not be necessary: https://github.com/errbit/errbit/issues/283
